#!/usr/bin/env bash
# A bash script that runs nginx as nginx user
# A bash script that configures nginx to listen on all active IP's on port 8080
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
