#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Set hostname
echo "web-02" > /etc/hostname
hostnamectl set-hostname web-02

# Configure custom HTTP response header for Nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /var/www/html;
        index index.html index.htm;
    }

    add_header X-Served-By \$hostname;
}
EOF

# Restart Nginx to apply changes
service  restart nginx
