#!/bin/bash
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# Check if all 4 parameters are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <file_path> <server_ip> <username> <destination_path>"
    exit 1
fi
# extract the parameter
file_path="$1"
server_ip="$2"
username="$3"
destination_path="$4"

# Transfer the file using secure copy
scp "$file_path" "$username@$server_ip:$destination_path"

#Confirm succeful transfer of the files
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully!"
else
    echo "Error transferring the file."
fi
