#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Return a page that writes  "Holberton School"

# install nginx
 sudo apt update
# install sudo and nano commands
 apt install sudo
 apt install nano
# modifying the nginx sites-available file
 sudo nano /etc/nginx/sites-available/default
# Reloading nginx to save the file
 sudo service nginx reload 
# Connecting to local host port 80; connection failed
# Checking the status of nginx
 sudo service nginx status
 sudo service nginx start
# Checking if nginx is configured
 sudo nginx -t
# Requesting the page response using curl
 curl localhost 
#displays Holberton School
