#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School"

# Update package repositories
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Create index.html file with content "Holberton School"
echo 'Holberton School' > /var/www/html/index.html

# Restart Nginx service
sudo service nginx restart

# Verify Nginx is running and returning 200 OK
curl -Is http://localhost | head -1

# Verify Nginx root page contains "Holberton School"
curl -s http://localhost | grep "Holberton School"
