#!/bin/bash

Update package repositories
sudo apt-get update

Install Nginx
sudo apt-get install nginx -y

Create index.html file with content "Holberton School"
echo 'Holberton School' > /var/www/html/index.html

Create a configuration file for redirection
sudo sh -c 'cat > /etc/nginx/sites-available/redirect' << EOF
server {
    listen 80;
    server_name _;

CopyReplit
location /redirect_me {
    return 301 http://www.example.com;
}

location / {
    root /var/www/html;
}
}
EOF

Create symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

Restart Nginx service
sudo service nginx restart

echo "Nginx has been configured to redirect /redirect_me to http://www.example.com with a 301 status code."
